import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import {
  DndContext,
  DragOverlay,
  PointerSensor,
  TouchSensor,
  useDraggable,
  useDroppable,
  useSensor,
  useSensors,
} from '@dnd-kit/core'
import FeedScreen from '../screens/FeedScreen.jsx'

/* ───────── Tiger character assets ───────── */
const TIGER = {
  happy:   '/tigers/tiger-happy.png',
  talk:    '/tigers/tiger-talk.png',
  point:   '/tigers/tiger-point.png',
  magnify: '/tigers/tiger-magnify.png',
  scared:  '/tigers/tiger-scared.png',
  run:     '/tigers/tiger-run.png',
}

/* ───────── Demo content ───────── *
 * Shape mirrors entries in src/data/headlines.json so it can be fed
 * straight into the real <FeedScreen /> during the tutorial. */
const DEMO_HEADLINE = {
  id: 'tutorial-h1',
  headline: 'Penguin in Boston Trained to Buy Snacks From Vending Machine Every Day',
  video: '/videos/penguin.mp4',
  thumbnail: '🐧',
  thumbnailGradient: 'from-cyan-300 via-sky-600 to-indigo-900',
  fakeSource: 'WildWireDaily',
  sourceVibe: 'news',
  engagement: { likes: 1_500_000, shares: 320_000, timestamp: '3h ago' },
}

const DEMO_EVIDENCE = {
  id: 'demo-e1',
  type: 'article',
  title: 'BBC Fact Check: viral "vending machine penguin" video is AI-generated',
  source: 'BBC Fact Check',
  body:
    'A viral clip claiming a penguin in Boston operates a vending machine has been confirmed as AI-generated by the BBC Fact Check team. Visual artifacts include flippers that flicker between frames, and a vending machine logo that warps when the camera pans.\n\nThe posting account, @PenguinBuddy, was created two weeks ago and has shared three prior AI fakes. Aquariums and zoos in the Boston area told the BBC they have no record of any such bird.',
}

const TAG_OPTIONS = [
  { id: 'supports', emoji: '✅', label: 'Supports', hint: 'Backs up the claim' },
  { id: 'refutes',  emoji: '❌', label: 'Refutes',  hint: 'Debunks the claim' },
  { id: 'sketchy',  emoji: '⚠️', label: 'Sketchy',  hint: 'Looks unreliable' },
]

const VERDICTS = [
  { id: 'TRUE',         label: 'TRUE',      emoji: '✅' },
  { id: 'FALSE',        label: 'FALSE',     emoji: '❌' },
  { id: 'MISLEADING',   label: 'MISLEAD',   emoji: '⚠️' },
  { id: 'SATIRE',       label: 'SATIRE',    emoji: '😂' },
  { id: 'UNVERIFIABLE', label: 'UNVERIF',   emoji: '❓' },
]

/* ───────── Step script — phase, tiger pose, what tiger says, what action ends the step ───────── */
const STEPS = [
  // FEED phase
  { phase: 'feed',    tiger: 'happy',   text: "Hi there! I'm Detective Stripes 🐯. Welcome to TruthScroll!", action: 'next' },
  { phase: 'feed',    tiger: 'talk',    text: "Your job is to spot fake news. Real story? Total lie? You decide.", action: 'next' },
  { phase: 'feed',    tiger: 'point',   text: "See this pink magnifying glass? Tap INVESTIGATE to open a case.", action: 'investigate', highlight: 'investigate' },

  // INVESTIGATION phase
  { phase: 'invest',  tiger: 'talk',    text: "Welcome to your detective board. Down here are EVIDENCE folders.", action: 'next', highlight: 'folders' },
  { phase: 'invest',  tiger: 'point',   text: "Tap the folder to open it up and read what's inside.", action: 'open-folder', highlight: 'folder' },
  { phase: 'invest',  tiger: 'magnify', text: "Read it carefully... then close it with the × when you're done.", action: 'close-viewer', highlight: 'viewer' },
  { phase: 'invest',  tiger: 'point',   text: "Now DRAG the folder up onto the corkboard to pin it.", action: 'pin-folder', highlight: 'opened-folder' },
  { phase: 'invest',  tiger: 'point',   text: "Tag your pin! Does this evidence SUPPORT, REFUTE, or look SKETCHY?", action: 'tag-folder', highlight: 'tag-modal' },
  { phase: 'invest',  tiger: 'talk',    text: "Time for your VERDICT. Is the story true, false, or somewhere in between?", action: 'pick-verdict', highlight: 'verdict' },
  { phase: 'invest',  tiger: 'happy',   text: "Awesome! Hit SUBMIT to lock in your answer.", action: 'submit', highlight: 'submit' },

  // RESULTS phase
  { phase: 'results', tiger: 'magnify', text: "Boom! Here's your score. Right answers + fast finishes = more XP.", action: 'next' },
  { phase: 'results', tiger: 'happy',   text: "You're ready, Detective! Tap FINISH to play for real.", action: 'finish' },
]

export default function Tutorial({ onFinish, totalXP = 0, rank = null }) {
  const [step, setStep] = useState(0)
  // Folder state machine inside the demo investigation
  const [folderOpened, setFolderOpened] = useState(false)
  const [folderPinned, setFolderPinned] = useState(false)
  const [folderTag, setFolderTag] = useState(null)
  const [viewerOpen, setViewerOpen] = useState(false)
  const [tagModalOpen, setTagModalOpen] = useState(false)
  const [verdict, setVerdict] = useState(null)

  const current = STEPS[step]
  const goNext = () => setStep((s) => Math.min(s + 1, STEPS.length - 1))

  /* ───────── action gates — only the current step's expected action actually advances ───────── */
  const onTapNext       = () => { if (current.action === 'next') goNext() }
  const onInvestigate   = () => { if (current.action === 'investigate') goNext() }
  const onOpenFolder    = () => {
    if (current.action === 'open-folder') {
      setFolderOpened(true)
      setViewerOpen(true)
      goNext()
    }
  }
  const onCloseViewer   = () => {
    if (current.action === 'close-viewer') {
      setViewerOpen(false)
      goNext()
    }
  }
  const onPinFolder     = () => {
    if (current.action === 'pin-folder') {
      setFolderPinned(true)
      setTagModalOpen(true)
      goNext()
    }
  }
  const onPickTag       = (tagId) => {
    if (current.action === 'tag-folder') {
      setFolderTag(tagId)
      setTagModalOpen(false)
      goNext()
    }
  }
  const onPickVerdict   = (v) => {
    if (current.action === 'pick-verdict') {
      setVerdict(v)
      goNext()
    }
  }
  const onSubmit        = () => { if (current.action === 'submit') goNext() }
  const onTapFinish     = () => onFinish?.()

  /* ───────── render the right stage for the current phase ───────── */
  return (
    <div className="relative h-[100dvh] w-full overflow-hidden bg-feed-bg text-white no-select">
      <AnimatePresence mode="wait">
        {current.phase === 'feed' && (
          <FeedStage
            key="feed"
            current={current}
            totalXP={totalXP}
            rank={rank}
            onInvestigate={onInvestigate}
          />
        )}
        {current.phase === 'invest' && (
          <InvestStage
            key="invest"
            current={current}
            folderOpened={folderOpened}
            folderPinned={folderPinned}
            folderTag={folderTag}
            verdict={verdict}
            onOpenFolder={onOpenFolder}
            onPinFolder={onPinFolder}
            onPickVerdict={onPickVerdict}
            onSubmit={onSubmit}
          />
        )}
        {current.phase === 'results' && (
          <ResultsStage
            key="results"
            current={current}
            verdict={verdict}
            tag={folderTag}
            onFinish={onTapFinish}
          />
        )}
      </AnimatePresence>

      {/* Modals — overlays on top of the investigation stage */}
      <AnimatePresence>
        {viewerOpen && (
          <EvidenceModal
            key="viewer-modal"
            item={DEMO_EVIDENCE}
            onClose={onCloseViewer}
            canClose={current.action === 'close-viewer'}
          />
        )}
      </AnimatePresence>
      <AnimatePresence>
        {tagModalOpen && (
          <TagModal
            key="tag-modal"
            item={DEMO_EVIDENCE}
            onPick={onPickTag}
            highlighted={current.highlight === 'tag-modal'}
          />
        )}
      </AnimatePresence>

      {/* Persistent tiger + speech bubble */}
      <TigerCoach
        current={current}
        step={step}
        total={STEPS.length}
        onNext={onTapNext}
        onFinish={onTapFinish}
      />
    </div>
  )
}

/* ─────────────────────────────────────────────────────────────────
 * TigerCoach — the character on the right with a speech bubble and
 * a contextual control button (Next / Finish) when the step doesn't
 * require an in-stage action.
 * ────────────────────────────────────────────────────────────── */
function TigerCoach({ current, step, total, onNext, onFinish }) {
  const showButton = current.action === 'next' || current.action === 'finish'
  const isFinish = current.action === 'finish'

  return (
    <div className="pointer-events-none absolute inset-0 z-[200]">
      {/* Tiger */}
      <motion.div
        key={current.tiger}
        initial={{ opacity: 0, x: 60, y: 10 }}
        animate={{ opacity: 1, x: 0, y: 0 }}
        transition={{ type: 'spring', stiffness: 220, damping: 22 }}
        className="absolute bottom-0 right-0 sm:right-2 z-[201] pointer-events-none select-none"
      >
        <img
          src={TIGER[current.tiger]}
          alt=""
          draggable={false}
          className="h-[220px] sm:h-[300px] lg:h-[340px] w-auto drop-shadow-[0_10px_22px_rgba(0,0,0,0.5)]"
        />
      </motion.div>

      {/* Speech bubble */}
      <motion.div
        key={`bubble-${step}`}
        initial={{ opacity: 0, y: 12, scale: 0.96 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ type: 'spring', stiffness: 280, damping: 24 }}
        className="pointer-events-auto absolute z-[202] bottom-[210px] sm:bottom-[260px] lg:bottom-[290px] right-3 sm:right-[230px] left-3 sm:left-auto max-w-[420px] sm:max-w-[380px]"
      >
        <div className="relative rounded-2xl bg-white text-[#1c1b18] px-4 py-3 sm:px-5 sm:py-4 shadow-[0_20px_50px_rgba(0,0,0,0.45)] ring-2 ring-black/15">
          <div className="text-[10px] font-mono uppercase tracking-widest text-black/45 mb-1">
            Detective Stripes · {step + 1}/{total}
          </div>
          <div className="font-serif text-[15px] sm:text-[17px] leading-snug text-black/85">
            {current.text}
          </div>

          {showButton && (
            <div className="mt-3 flex justify-end">
              <button
                onClick={isFinish ? onFinish : onNext}
                className="press rounded-full bg-feed-lime px-5 py-2 font-display text-[13px] font-bold uppercase tracking-widest text-black shadow-[0_0_18px_rgba(204,255,0,0.55)] hover:bg-feed-lime/90"
              >
                {isFinish ? 'Finish →' : 'Next →'}
              </button>
            </div>
          )}

          {/* Bubble tail — points down-right to tiger */}
          <div className="hidden sm:block absolute -right-3 bottom-6 w-0 h-0 border-y-[10px] border-y-transparent border-l-[16px] border-l-white" />
          <div className="sm:hidden absolute -bottom-3 right-14 w-0 h-0 border-x-[10px] border-x-transparent border-t-[16px] border-t-white" />
        </div>

        {/* Skip — quiet, top-right of bubble */}
        <button
          onClick={onFinish}
          className="absolute -top-7 right-1 text-[10px] font-mono uppercase tracking-widest text-white/55 hover:text-white"
        >
          skip tutorial →
        </button>
      </motion.div>
    </div>
  )
}

/* ─────────────────────────────────────────────────────────────────
 * FeedStage — uses the real <FeedScreen /> with a single demo headline,
 * so the tutorial home looks pixel-identical to the real iPhone page.
 *
 * A transparent click-blocking layer covers the feed until the user
 * reaches the "tap INVESTIGATE" step; on that step the layer drops so
 * the real Investigate button is reachable and its onInvestigate
 * advances the tutorial.
 * ────────────────────────────────────────────────────────────── */
function FeedStage({ current, totalXP, rank, onInvestigate }) {
  const investigateActive = current.action === 'investigate'
  const noop = () => {}
  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      transition={{ duration: 0.3 }}
      className="absolute inset-0"
    >
      <FeedScreen
        headlines={[DEMO_HEADLINE]}
        completedIds={new Set()}
        runningScore={0}
        totalXP={totalXP}
        rank={rank}
        onInvestigate={onInvestigate}
        onRefresh={noop}
      />

      {/* Block all clicks on the feed until it's time to investigate.
          The tiger speech bubble (z-[202]) still floats above and stays
          interactive thanks to pointer-events-auto on its container. */}
      {!investigateActive && (
        <div className="absolute inset-0 z-[150] bg-black/15 pointer-events-auto" />
      )}

      {/* Lime ring around the investigate button on its highlight step.
          We mirror FeedScreen's full wrapper chain (scale-[1.06] outer, then
          scale-[1.03] iPhone-screen inset) so the ring lives in the SAME
          transformed coordinate space as the button itself — px offsets
          inside line up regardless of viewport size.

          The FeedCard button column sits at right-2 bottom-20 with Investigate
          at the TOP of the stack:
            Scroll   (~56px)
            ──gap-4 (16)──
            Like     (~56px)
            ──gap-4 (16)──
            Investigate icon ~48px (then mt-1.5 + 13px label below)
          So Investigate icon center ≈ 80 + 56 + 16 + 56 + 16 + 13 + 6 + 24 = 267
          px above the feed bottom; a 56px ring centered on it sits at
          bottom-[239px]. */}
      {current.highlight === 'investigate' && (
        <div className="pointer-events-none absolute inset-0 z-[155]">
          <div className="relative h-full w-full sm:absolute sm:left-1/2 sm:top-1/2 sm:-translate-x-1/2 sm:-translate-y-1/2 sm:h-[max(100dvh,calc(100vw*9/16))] sm:w-[max(100vw,calc(100dvh*16/9))] sm:scale-[1.06]">
            <div className="absolute inset-0 sm:inset-auto sm:left-[40.4%] sm:top-[15.6%] sm:w-[19.8%] sm:h-[72.7%] sm:scale-[1.03] sm:origin-center">
              <motion.span
                initial={{ scale: 0.6, opacity: 0 }}
                animate={{ scale: [1, 1.15, 1], opacity: 1 }}
                transition={{ duration: 1.4, repeat: Infinity, ease: 'easeInOut' }}
                className="absolute right-[12px] bottom-[239px] block h-14 w-14 rounded-full ring-4 ring-feed-lime shadow-[0_0_40px_rgba(204,255,0,0.7)]"
              />
            </div>
          </div>
        </div>
      )}
    </motion.div>
  )
}

/* ─────────────────────────────────────────────────────────────────
 * InvestStage — corkboard + a single evidence folder.
 * Mirrors the real screen, INCLUDING the dnd-kit drag-to-pin
 * mechanic. The folder must be opened (read) first; once opened it
 * becomes draggable; dropping it on the board fires onPinFolder.
 * ────────────────────────────────────────────────────────────── */
function InvestStage({ current, folderOpened, folderPinned, folderTag, verdict, onOpenFolder, onPinFolder, onPickVerdict, onSubmit }) {
  const submitEnabled = current.action === 'submit'
  const dragArmed = current.action === 'pin-folder' && folderOpened && !folderPinned

  // Same sensor setup the real InvestigationScreen uses, so drag feel is identical.
  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 4 } }),
    useSensor(TouchSensor,   { activationConstraint: { delay: 120, tolerance: 6 } }),
  )

  const [activeDragId, setActiveDragId] = useState(null)
  const handleDragStart = (event) => setActiveDragId(event.active.id)
  const handleDragEnd = (event) => {
    setActiveDragId(null)
    if (event.over?.id === 'tutorial-board' && dragArmed) {
      onPinFolder()
    }
  }

  return (
    <DndContext sensors={sensors} onDragStart={handleDragStart} onDragEnd={handleDragEnd}>
      <motion.div
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
        transition={{ duration: 0.3 }}
        className="absolute inset-0 bg-[#21252d] flex flex-col"
      >
        {/* Top bar — looks like the real timer bar but inert */}
        <div className="relative z-20 flex items-center justify-between gap-3 bg-black/35 px-4 sm:px-6 py-3 pt-[max(env(safe-area-inset-top),14px)] backdrop-blur-md shadow-md border-b border-black/20">
          <div className="flex items-center gap-1.5 rounded-full border-2 border-white/25 bg-black/55 px-4 py-2 text-[14px] font-bold uppercase tracking-widest text-white shadow-md">
            ← Back
          </div>
          <div className="flex items-center gap-2 rounded-full border-2 border-white/25 bg-black/55 px-4 py-2 font-mono text-[16px] tabular-nums font-bold text-white shadow-md">
            ⏱ 5:00
          </div>
        </div>

        {/* Cork board */}
        <div className="relative flex-1 w-full p-4 sm:p-6 overflow-hidden flex flex-col items-center justify-center">
          <DroppableBoard armed={dragArmed} highlight={current.highlight === 'opened-folder' && folderOpened}>
            {/* Connecting string when pinned */}
            {folderPinned && (
              <svg className="absolute inset-0 w-full h-full pointer-events-none z-0" style={{ filter: 'drop-shadow(0 4px 6px rgba(0,0,0,0.5))' }}>
                <line x1="50%" y1="50%" x2="22%" y2="35%" stroke="#d93829" strokeWidth="2.5" strokeLinecap="round" strokeDasharray="6 4" />
              </svg>
            )}

            {/* Central polaroid */}
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 flex flex-col items-center justify-center p-3 sm:p-4 bg-[#ebd9c8] pb-8 sm:pb-10 shadow-[0_10px_20px_rgba(0,0,0,0.3)] rotate-[-1deg] z-10 max-w-[180px] sm:max-w-[220px]">
              <div className="absolute -top-3 left-1/2 -translate-x-1/2 w-3.5 h-3.5 rounded-full bg-[#c82424] shadow-[inset_-2px_-2px_4px_rgba(0,0,0,0.4),0_4px_4px_rgba(0,0,0,0.3)] z-20" />
              <div className="w-32 h-32 sm:w-44 sm:h-44 bg-white pt-2 px-2 overflow-hidden">
                <div className="w-full h-full bg-black flex items-center justify-center text-5xl sm:text-6xl">{DEMO_HEADLINE.thumbnail}</div>
              </div>
              <div className="mt-3 font-chaos text-[11px] sm:text-[12px] text-[#5a4c40] text-center leading-snug px-1 line-clamp-3">
                {DEMO_HEADLINE.headline}
              </div>
              <div className="mt-1 text-[9px] font-mono text-[#8a7c6c] uppercase tracking-widest">
                @{DEMO_HEADLINE.fakeSource}
              </div>
            </div>

            {/* Pinned folder on the board */}
            {folderPinned && (
              <motion.div
                initial={{ opacity: 0, scale: 0.7, y: 30 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                transition={{ type: 'spring', stiffness: 220, damping: 22 }}
                className="absolute z-20"
                style={{ top: '35%', left: '22%', transform: 'translate(-50%, -50%) rotate(-4deg)' }}
              >
                <PinnedNote item={DEMO_EVIDENCE} tag={folderTag} />
              </motion.div>
            )}
          </DroppableBoard>
        </div>

        {/* Verdict floating bar — appears once a pin is on the board */}
        {folderPinned && folderTag && (
          <motion.div
            initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }}
            transition={{ type: 'spring', stiffness: 220, damping: 22 }}
            className="absolute bottom-[270px] sm:bottom-[310px] left-0 right-0 px-3 z-30 flex justify-center pointer-events-none"
          >
            <div className={`bg-[#fdfcf9] p-2 sm:p-2.5 rounded-2xl shadow-[0_10px_30px_rgba(0,0,0,0.4)] flex items-center gap-1.5 sm:gap-2 border-2 pointer-events-auto ${
              (current.highlight === 'verdict' || current.highlight === 'submit') ? 'border-feed-lime ring-2 ring-feed-lime/60' : 'border-[#e6ded3]'
            }`}>
              {VERDICTS.map((v) => {
                const active = verdict === v.id
                return (
                  <button
                    key={v.id}
                    onClick={() => onPickVerdict(v.id)}
                    disabled={current.action !== 'pick-verdict' && !active}
                    className={`press flex flex-col items-center justify-center rounded-xl px-2 sm:px-3 py-1.5 sm:py-2 transition-all ${
                      active
                        ? 'bg-[#1c1b18] text-white scale-105 border-2 border-[#1c1b18]'
                        : 'bg-black/5 text-[#1c1b18] hover:bg-black/10 border-2 border-transparent'
                    }`}
                  >
                    <span className="text-[18px] sm:text-[20px] leading-none mb-0.5">{v.emoji}</span>
                    <span className="text-[9px] sm:text-[10px] font-bold uppercase tracking-wider">{v.label}</span>
                  </button>
                )
              })}
              <button
                onClick={onSubmit}
                disabled={!submitEnabled}
                className={`press ml-1 rounded-xl px-3 sm:px-4 py-2.5 font-display text-[12px] sm:text-[13px] font-bold uppercase tracking-widest transition-all ${
                  submitEnabled
                    ? 'bg-red-600 text-white shadow-md hover:bg-red-700 ring-2 ring-feed-lime animate-pulse'
                    : verdict ? 'bg-black/30 text-white/60' : 'bg-black/10 text-black/30 cursor-not-allowed'
                }`}
              >
                Submit
              </button>
            </div>
          </motion.div>
        )}

        {/* Bottom evidence folder drawer */}
        <div className={`h-[230px] sm:h-[260px] shrink-0 bg-[#2a241e] border-t-4 border-[#1e1914] rounded-t-[2rem] shadow-[0_-10px_40px_rgba(0,0,0,0.6)] z-40 relative flex flex-col transition-all ${
          current.highlight === 'folders' ? 'ring-4 ring-feed-lime/60' : ''
        }`}>
          <div className="flex items-center justify-between px-5 pt-3 pb-2">
            <div className="font-serif text-[16px] sm:text-[18px] text-[#e2cfb6] font-semibold flex items-center gap-2">
              <span>Evidence Folders</span>
              <span className="bg-[#1e1914] text-[#a89074] text-[11px] px-2 py-0.5 rounded-full font-mono font-bold">
                {folderPinned ? 0 : 1} left
              </span>
            </div>
            {folderOpened && !folderPinned && (
              <div className="text-[11px] sm:text-[12px] font-mono tracking-widest text-[#a89074] animate-pulse">
                DRAG TO PIN ↑
              </div>
            )}
          </div>

          <div className="flex-1 flex items-end gap-4 px-5 pb-3">
            {!folderPinned ? (
              folderOpened ? (
                <DraggableOpenedFolder
                  item={DEMO_EVIDENCE}
                  highlight={current.highlight === 'opened-folder'}
                  disabled={!dragArmed}
                />
              ) : (
                <ClosedFolder
                  item={DEMO_EVIDENCE}
                  highlight={current.highlight === 'folder'}
                  onClick={onOpenFolder}
                />
              )
            ) : (
              <div className="w-full h-full flex flex-col items-center justify-center text-[#a89074]/50 border-2 border-dashed border-[#a89074]/20 rounded-xl mb-2">
                <span className="text-2xl mb-1">🗄️</span>
                <span className="font-serif text-xs italic">All evidence pinned</span>
              </div>
            )}
          </div>
        </div>
      </motion.div>

      <DragOverlay dropAnimation={{ duration: 250, easing: 'cubic-bezier(0.18, 0.67, 0.6, 1.22)' }}>
        {activeDragId === 'tutorial-folder' ? (
          <OpenedFolderVisual item={DEMO_EVIDENCE} dragging />
        ) : null}
      </DragOverlay>
    </DndContext>
  )
}

/* The corkboard styled as a droppable target. Lights up while the user
 * is actively dragging the opened folder over it. */
function DroppableBoard({ children, armed, highlight }) {
  const { isOver, setNodeRef } = useDroppable({ id: 'tutorial-board' })
  return (
    <div
      ref={setNodeRef}
      className={`relative w-full max-w-3xl aspect-[4/3] sm:aspect-[16/10] rounded-[1.5rem] shadow-[0_25px_50px_rgba(0,0,0,0.6)] border-[14px] sm:border-[22px] border-[#ca7c45] bg-[#d38b58] overflow-hidden transition-shadow ${
        armed && isOver ? 'ring-4 ring-feed-lime shadow-[0_0_60px_rgba(204,255,0,0.6)]' :
        armed ? 'ring-2 ring-feed-lime/40' :
        highlight ? '' : ''
      }`}
    >
      <div className="absolute inset-0 border-[6px] sm:border-[8px] border-[#9e5623] pointer-events-none z-30" />
      <div className="absolute inset-0 opacity-[0.25] mix-blend-multiply pointer-events-none" style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")` }} />
      {children}
    </div>
  )
}

/* Closed folder — tap to open. */
function ClosedFolder({ item, highlight, onClick }) {
  return (
    <button
      onClick={onClick}
      className={`press relative flex flex-col w-[150px] sm:w-[170px] h-[160px] sm:h-[180px] shrink-0 transition-transform ${
        highlight ? 'ring-4 ring-feed-lime ring-offset-2 ring-offset-[#2a241e] -translate-y-3 animate-pulse' : 'hover:-translate-y-2'
      }`}
    >
      <div className="w-[50%] h-6 bg-[#d9af7a] rounded-t-lg border border-[#bc915a] border-b-0 self-start ml-2 z-10 flex items-center px-2.5">
        <span className="text-[10px] font-mono font-bold text-[#5c4021] truncate uppercase">ARTICLE</span>
      </div>
      <div className="flex-1 bg-gradient-to-b from-[#e8c089] to-[#d6a566] border border-[#bc915a] rounded-b-lg rounded-tr-lg p-2.5 flex flex-col shadow-lg relative -mt-[1px] z-20">
        <div className="absolute top-2.5 left-2.5 right-2.5 bottom-7 bg-[#fdfcf9]/95 rounded-sm border border-[#e6ded3] p-2 overflow-hidden shadow-inner rotate-1">
          <div className="text-[20px] mb-1 leading-none opacity-70">📰</div>
          <div className="text-[12px] font-bold text-black/60 line-clamp-3 leading-snug font-serif text-left">
            {item.title}
          </div>
        </div>
        <div className="absolute bottom-0 left-0 right-0 h-[55%] bg-gradient-to-t from-[#c99553] to-[#e0b77e] rounded-b-lg border-t border-white/20 flex items-end p-2 pb-3">
          <div className="text-[10px] font-mono text-[#4a3116] uppercase tracking-wider truncate w-full text-center opacity-90 font-semibold">
            {item.source}
          </div>
        </div>
        <div className="absolute inset-0 rounded-b-lg rounded-tr-lg bg-[#2a1a08]/30 z-30 pointer-events-none" />
        <div className="absolute top-2 right-2 z-40 pointer-events-none">
          <div className="rounded-full bg-[#c82424] text-white w-8 h-8 flex items-center justify-center text-[16px] shadow-md ring-2 ring-white/30">🔒</div>
        </div>
        <div className="absolute inset-x-0 bottom-[55%] z-40 pointer-events-none flex justify-center">
          <div className="rounded-full bg-black/85 text-white text-[10px] font-mono font-bold uppercase tracking-widest px-2 py-0.5 shadow ring-1 ring-white/10">
            Tap to open
          </div>
        </div>
      </div>
    </button>
  )
}

/* Opened folder — draggable via @dnd-kit. Drop on the board to pin. */
function DraggableOpenedFolder({ item, highlight, disabled }) {
  const { attributes, listeners, setNodeRef, isDragging } = useDraggable({
    id: 'tutorial-folder',
    disabled,
  })
  return (
    <div
      ref={setNodeRef}
      {...attributes}
      {...listeners}
      role="button"
      aria-label={`Drag to pin: ${item.title}`}
      style={{ opacity: isDragging ? 0 : 1, touchAction: 'none' }}
      className={`shrink-0 transition-transform ${highlight && !isDragging ? '-translate-y-2' : ''}`}
    >
      <OpenedFolderVisual item={item} highlight={highlight} />
    </div>
  )
}

/* The visual the opened folder uses both in the drawer and in the DragOverlay. */
function OpenedFolderVisual({ item, highlight, dragging }) {
  return (
    <div
      className={`relative w-[150px] sm:w-[170px] h-[160px] sm:h-[180px] bg-[#fdfcf9] border border-[#e6ded3] shadow-[0_8px_18px_rgba(0,0,0,0.28)] rotate-[-1.5deg] text-left transition-transform ${
        dragging ? 'scale-105 rotate-2 shadow-2xl' :
        highlight ? 'ring-4 ring-feed-lime animate-pulse' : ''
      }`}
    >
      <div className="absolute top-0 right-0 w-6 h-6 bg-[#e8e2d3]" style={{ clipPath: 'polygon(100% 0, 100% 100%, 0 0)' }} />
      <div className="absolute -top-2 left-1.5 z-30 pointer-events-none rotate-[-14deg]">
        <div className="rounded-sm border-2 border-emerald-700/80 text-emerald-700 bg-emerald-50/85 text-[10px] sm:text-[11px] font-bold uppercase tracking-[0.16em] px-1.5 py-0.5 shadow-sm">
          Read ✓
        </div>
      </div>
      <div className="absolute inset-x-0 top-8 px-3">
        <div className="text-[22px] leading-none mb-1.5">📰</div>
        <div className="text-[12px] sm:text-[13px] font-bold leading-snug text-black/85 line-clamp-4 font-serif">
          {item.title}
        </div>
      </div>
      <div className="absolute bottom-0 inset-x-0 border-t border-black/10 bg-black/[0.02] px-2 py-1">
        <div className="text-[10px] font-mono text-black/60 uppercase tracking-widest truncate">
          {item.source}
        </div>
      </div>
      <div className="absolute bottom-7 right-2 pointer-events-none text-[16px] opacity-50">↗</div>
    </div>
  )
}

/* The note as it sits pinned on the corkboard. */
function PinnedNote({ item, tag }) {
  const tagInfo = tag ? TAG_OPTIONS.find(t => t.id === tag) : null
  return (
    <div className="relative bg-[#fdfcf9] w-[140px] sm:w-[160px] p-2 sm:p-2.5 shadow-[0_6px_18px_rgba(0,0,0,0.25)] border-2 border-[#e6ded3] text-[#1c1b18]">
      <div className="absolute -top-3 left-1/2 -translate-x-1/2 w-4 h-4 rounded-full bg-[#c82424] shadow-[inset_-2px_-2px_4px_rgba(0,0,0,0.4),0_4px_4px_rgba(0,0,0,0.3)] z-30" />
      {tagInfo && (
        <div className="absolute -right-2.5 -top-2.5 rotate-[6deg] z-30 bg-[#fef3c7] border-2 border-amber-300 shadow-md px-1.5 py-0.5 text-[18px] flex items-center">
          <span>{tagInfo.emoji}</span>
        </div>
      )}
      <div className="text-[22px] mb-1">📰</div>
      <div className="text-[11px] sm:text-[12px] font-bold text-black/90 line-clamp-3 leading-snug font-serif">
        {item.title}
      </div>
      <div className="mt-1.5 pt-1.5 border-t border-black/10 text-[9px] font-mono text-black/55 uppercase tracking-widest truncate">
        {item.source}
      </div>
    </div>
  )
}

/* ─────────────────────────────────────────────────────────────────
 * EvidenceModal — simplified read-the-doc overlay.
 * ────────────────────────────────────────────────────────────── */
function EvidenceModal({ item, onClose, canClose }) {
  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      transition={{ duration: 0.18 }}
      className="fixed inset-0 z-[120] bg-black/70 backdrop-blur-sm flex items-center justify-center p-3 sm:p-6"
      onClick={canClose ? onClose : undefined}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.96, y: 12 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.97, y: 6 }}
        transition={{ duration: 0.2, ease: [0.22, 0.61, 0.36, 1] }}
        onClick={(e) => e.stopPropagation()}
        className="relative w-full max-w-[640px] max-h-[80dvh] flex flex-col rounded-2xl bg-[#fdfcf9] text-[#1c1b18] shadow-[0_30px_80px_-10px_rgba(0,0,0,0.6)] ring-1 ring-black/10 overflow-hidden"
      >
        <div className="relative flex items-center gap-3 border-b border-black/10 bg-white/85 backdrop-blur px-5 py-3">
          <div className="min-w-0 flex-1 truncate text-[13px] font-mono uppercase tracking-widest text-black/65">
            {item.source}
          </div>
          <button
            onClick={onClose}
            disabled={!canClose}
            className={`press shrink-0 rounded-full w-11 h-11 flex items-center justify-center text-[22px] leading-none font-bold transition ${
              canClose ? 'bg-feed-lime text-black ring-2 ring-feed-lime animate-pulse hover:bg-feed-lime/90' : 'bg-black/5 text-black/40'
            }`}
            aria-label="Close"
          >
            ×
          </button>
        </div>
        <div className="flex-1 overflow-y-auto px-5 sm:px-6 py-4 sm:py-5">
          <div className="font-serif text-[20px] sm:text-[22px] font-bold leading-snug">
            {item.title}
          </div>
          <div className="mt-3 font-serif text-[15px] sm:text-[16px] leading-relaxed text-black/80 whitespace-pre-line">
            {item.body}
          </div>
        </div>
      </motion.div>
    </motion.div>
  )
}

/* ─────────────────────────────────────────────────────────────────
 * TagModal — simplified tag picker (no note field in tutorial).
 * ────────────────────────────────────────────────────────────── */
function TagModal({ item, onPick, highlighted }) {
  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      transition={{ duration: 0.18 }}
      className="fixed inset-0 z-[125] bg-black/75 backdrop-blur-sm flex items-end sm:items-center justify-center p-3 sm:p-6"
    >
      <motion.div
        initial={{ opacity: 0, y: 30, scale: 0.96 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: 20, scale: 0.97 }}
        transition={{ duration: 0.22 }}
        className={`relative w-full max-w-[520px] flex flex-col rounded-2xl bg-[#fdfcf9] text-[#1c1b18] shadow-[0_30px_80px_-10px_rgba(0,0,0,0.6)] overflow-hidden ${
          highlighted ? 'ring-4 ring-feed-lime' : 'ring-1 ring-black/10'
        }`}
      >
        <div className="px-5 py-4 border-b border-black/10 bg-[#fef3c7] flex items-start gap-3">
          <div className="text-[28px] leading-none mt-0.5">📌</div>
          <div className="min-w-0 flex-1">
            <div className="text-[11px] font-mono uppercase tracking-widest text-black/60">
              Tag this pin
            </div>
            <div className="mt-1 font-serif text-[16px] font-bold leading-snug line-clamp-2">
              {item.title}
            </div>
          </div>
        </div>
        <div className="px-5 py-5">
          <div className="text-[11px] font-mono uppercase tracking-widest text-black/60 mb-2.5">
            Sticky tag
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
            {TAG_OPTIONS.map((t) => (
              <button
                key={t.id}
                onClick={() => onPick(t.id)}
                className="press flex items-center gap-2.5 rounded-xl border-2 border-[#e6ded3] bg-white px-3.5 py-3 text-left transition-colors hover:border-black/30"
              >
                <span className="text-[24px] leading-none">{t.emoji}</span>
                <div className="min-w-0">
                  <div className="text-[13px] font-bold uppercase tracking-wider leading-tight">{t.label}</div>
                  <div className="text-[11px] leading-tight mt-0.5 text-black/55">{t.hint}</div>
                </div>
              </button>
            ))}
          </div>
          <div className="mt-3 text-[12px] italic text-black/55 leading-snug">
            Tip: a BBC Fact Check article that says the video is fake = REFUTES.
          </div>
        </div>
      </motion.div>
    </motion.div>
  )
}

/* ─────────────────────────────────────────────────────────────────
 * ResultsStage — tiny mock score card.
 * ────────────────────────────────────────────────────────────── */
function ResultsStage({ current, verdict, tag, onFinish }) {
  const correct = verdict === 'FALSE'
  const tagInfo = tag ? TAG_OPTIONS.find(t => t.id === tag) : null
  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      transition={{ duration: 0.3 }}
      className="absolute inset-0 bg-[#2b221a] flex items-center justify-center p-4 sm:p-8"
    >
      <div className="relative mx-auto w-full max-w-md">
        {/* Folder tab */}
        <div className="absolute -top-7 left-6 z-10 bg-[#e4c49d] rounded-t-xl border-t-[3px] border-l-[3px] border-r-[3px] border-[#8a5326] px-5 py-1.5 shadow-[0_-2px_8px_rgba(0,0,0,0.15)]">
          <span className="font-chaos text-[12px] tracking-widest text-[#5a3a1a] leading-none uppercase">
            Case File · Demo
          </span>
        </div>
        <div className="relative rounded-lg bg-[#e4c49d] border-[3px] border-[#8a5326] shadow-[0_18px_40px_-10px_rgba(0,0,0,0.55)] p-5 sm:p-6 text-[#3b2a1a]">
          <div className="text-[11px] font-mono uppercase tracking-widest text-[#5a3a1a]/70">
            Your verdict
          </div>
          <div className="mt-1 font-chaos text-[28px] sm:text-[32px] text-[#1c1b18]">
            {verdict || 'FALSE'} {correct ? '✅' : '·'}
          </div>
          <div className="mt-1 text-[13px] font-serif italic text-[#5a3a1a]">
            Correct answer: <strong>FALSE</strong>
          </div>

          <div className="mt-5 grid grid-cols-2 gap-3 text-[13px]">
            <ScoreRow label="Verdict" value={correct ? '+100' : '+25'} />
            <ScoreRow label="Evidence" value={tagInfo?.id === 'refutes' ? '+45' : '+15'} />
            <ScoreRow label="Speed bonus" value="+25" />
            <ScoreRow label="Total" value={correct ? '+170 XP' : '+65 XP'} bold />
          </div>

          <div className="mt-5 rounded-lg bg-white/60 border-2 border-[#8a5326]/30 p-3 text-[13px] leading-snug font-serif text-[#3b2a1a]">
            <strong>Why FALSE?</strong> The viral clip was AI-generated. The posting account is two weeks old with a track record of fakes, and Boston aquariums have no record of the bird.
          </div>

          {current.action === 'finish' && (
            <button
              onClick={onFinish}
              className="press mt-5 w-full rounded-full bg-feed-lime py-3.5 font-display text-[15px] font-bold uppercase tracking-widest text-black shadow-[0_0_20px_rgba(204,255,0,0.55)] hover:bg-feed-lime/90 animate-pulse"
            >
              Finish & start investigating →
            </button>
          )}
        </div>
      </div>
    </motion.div>
  )
}

function ScoreRow({ label, value, bold }) {
  return (
    <div className={`flex items-center justify-between rounded-md bg-white/40 border border-[#8a5326]/30 px-3 py-2 ${bold ? 'col-span-2 bg-[#fef3c7]' : ''}`}>
      <span className={`font-mono uppercase tracking-widest text-[11px] ${bold ? 'text-[#5a3a1a]' : 'text-[#5a3a1a]/80'}`}>{label}</span>
      <span className={`tabular-nums ${bold ? 'font-chaos text-[20px] text-[#1c1b18]' : 'font-bold text-[#1c1b18]'}`}>{value}</span>
    </div>
  )
}
